[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/jan)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x1c\0\0\a\x7f\0\0\x4\x37\0\0\0\b\0\0\0\x1c\0\0\x3\xba\0\0\x4/\0\0\0\0\x2\0\0\0\a\x80\0\0\0\x2\0\0\0\x1e\0\0\a}\0\0\x4\x35)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x14\0\0\x1\xc6\0\0\x1\xbc\0\0\0\x2\0\0\0\x16\0\0\x1\xc4\0\0\x1\xba\0\0\0\0\0\0\0\0\a\x80\0\0\0\x2\0\0\0\x16\0\0\x1\xc4\0\0\x1\xba)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1916 978)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 400)

[RecentsMRL]
list=file:///home/jan/dev/projects/framer_py/mov/IMG_2694.mov, file:///home/jan/dev/projects/framer_py/mov/IMG_2696.mov, file:///home/jan/dev/projects/framer_py/mov/IMG_2695.mov, file:///home/jan/dev/projects/framer_py/mov/IMG_2697.mov, file:///home/jan/dev/projects/framer_py/out.mp4, file:///home/jan/dev/projects/framer_py/mov/IMG_2693.mov, file:///home/jan/dev/projects/framer_py/mp4/v001.mp4, file:///home/jan/dev/projects/framer_py/mp4/v002.mp4, file:///home/jan/Downloads/498712881_9767795696629670_7730780726387973497_n.mp4, file:///home/jan/Downloads/856255-hd_1920_1080_25fps.mp4, file:///home/jan/Downloads/Sequence%2001_3.mp4, file:///home/jan/school/prprax1/synthetizer/dataset/noise-0/audio/0.1-0.9_A%3A3.7-4.2_B%3A.wav, file:///home/jan/school/prprax1/synthetizer/dataset/noise-0/audio/0.1-1.2_5%3A3.9-4.4_3%3A.wav, file:///home/jan/school/prprax1/synthetizer/dataset/noise-0/audio/0.1-1.1_4%3A2.4-2.8_D%3A.wav, file:///home/jan/school/prprax1/synthetizer/dataset/0.3-0.5__%3A2.8-3.0_B%3A.wav, file:///home/jan/school/prprax1/synthetizer/dataset/0.8-1.1_2%3A1.7-2.4__%3A.wav, file:///home/jan/school/prprax1/synthetizer/dataset/60.wav, file:///home/jan/school/prprax1/synthetizer/dataset/300.wav, file:///home/jan/school/prprax1/synthetizer/b.wav, file:///home/jan/school/prprax1/synthetizer/a.wav, file:///home/jan/school/prprax1/synthetizer/c.wav, file:///home/jan/school/prprax1/synthetizer/out.wav, file:///home/jan/school/prprax1/synthetizer/8.wav, file:///home/jan/school/prprax1/synthetizer/%23.wav, file:///home/jan/Downloads/UPA.wav, file:///home/jan/Documents/recordings/2025-01-14%2017-07-12.mkv, file:///home/jan/Documents/recordings/2025-01-14%2016-56-43.mkv, file:///home/jan/Documents/recordings/2025-01-14%2016-54-52.mkv, file:///home/jan/Documents/recordings/2025-01-14%2016-53-01.mkv, file:///home/jan/Documents/recordings/2025-01-14%2016-51-22.mkv
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
