[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/jan)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\b\0\0\0$\0\0\x3\xba\0\0\x4/\0\0\0\b\0\0\0$\0\0\x3\xba\0\0\x4/\0\0\0\0\0\0\0\0\a\x80\0\0\0\b\0\0\0$\0\0\x3\xba\0\0\x4/)

[Bookmarks]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\xe7\0\0\x1\x90\0\0\x4\x99\0\0\x2\xa7\0\0\x2\xe7\0\0\x1\x90\0\0\x4\x99\0\0\x2\xa7\0\0\0\0\0\0\0\0\a\x80\0\0\x2\xe7\0\0\x1\x90\0\0\x4\x99\0\0\x2\xa7)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x1c\0\0\x1\xc6\0\0\x1\xbc\0\0\0\x2\0\0\0\x1e\0\0\x1\xc4\0\0\x1\xba\0\0\0\0\0\0\0\0\a\x80\0\0\0\x2\0\0\0\x1e\0\0\x1\xc4\0\0\x1\xba)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(947 966)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 400)

[RecentsMRL]
list=file:///home/jan/dev/projects/vinx/out.mp4, file:///home/jan/dev/projects/vinx/out.mkv, file:///home/jan/dev/projects/vinx/examples/blank.mp4, file:///home/jan/school/KRY/pr1/xhrani03.mp3, file:///home/jan/dev/projects/vinx/examples/inverse.mp4, file:///home/jan/Downloads/Honza%20Hrani%C4%8Dka_s%20Video%20-%20Feb%204%2C%202026%281%29.mp3, file:///home/jan/Downloads/Honza%20Hrani%C4%8Dka_s%20Video%20-%20Feb%204%2C%202026.mp3, file:///home/jan/dev/projects/vinx/inverse.mp4, file:///home/jan/dev/projects/vinx/square_one.mp4, file:///home/jan/dev/projects/vinx/rows.mp4, file:///home/jan/dev/ref/vinx/out.mp4, file:///home/jan/tmp/out.mp4, file:///home/jan/dev/projects/vinx/trim.mp4, file:///home/jan/dev/projects/vinx/ou.mp4, file:///home/jan/fun/tidal/samples/bshihat/3%20Floating%20In%20Credit%20Hat.wav, file:///home/jan/fun/tidal/samples/bshihat/2%20Boiling%20In%20Dust%20Hats%202.wav, file:///home/jan/fun/tidal/samples/bshihat/1%20Boiling%20In%20Dust%20Hats%201.wav, file:///home/jan/fun/tidal/samples/bshihat/./3%20Floating%20In%20Credit%20Hat.wav, file:///home/jan/fun/tidal/samples/bshihat/./2%20Boiling%20In%20Dust%20Hats%202.wav, file:///home/jan/fun/tidal/samples/bshihat/./1%20Boiling%20In%20Dust%20Hats%201.wav, file:///home/jan/fun/tidal/samples/bsguitar/18%20Floating%20In%20Credit%20Guitar%202.wav, file:///home/jan/fun/tidal/samples/bsguitar/17%20Floating%20In%20Credit%20Guitar.wav, file:///home/jan/fun/tidal/samples/bsguitar/16%20Foyer%20Distortion%20Shard.wav, file:///home/jan/fun/tidal/samples/bsguitar/15%20Foyer%20Guitar%20Shard.wav, file:///home/jan/fun/tidal/samples/bsguitar/14%20Boiling%20In%20Dust%20Guitar%20Long.wav, file:///home/jan/fun/tidal/samples/bsguitar/13%20Boiling%20In%20Dust%20Guitar%20Short.wav, file:///home/jan/fun/tidal/samples/bsguitar/12%20Harsh%20Realm%20Guitar%20Roll.wav, file:///home/jan/fun/tidal/samples/bsguitar/11%20Harsh%20Realm%20Guitar%20Noise%20Riff.wav, file:///home/jan/fun/tidal/samples/bsguitar/10%20Harsh%20Realm%20Guitar%20Noise.wav, file:///home/jan/fun/tidal/samples/bsguitar/9%20Harsh%20Realm%20Guitar%20Noise%20Mid.wav
times=0, 0, 0, 0, 0, 0, 303597, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
